name: project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  dash_chat_2: ^0.0.20
  chat_gpt_sdk: ^3.0.4
  #flutter_dialogflow: ^0.1.3
  #bubble: ^1.1.9+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/women.png
    - assets/child.png
    - assets/hand.png
    - assets/wingman_logo.png
    - assets/wingman.png
    - assets/swasti.png
    - assets/about_us.png
    - assets/PRERNA_SAMAJIK_SANSTHA_NGO.png
    - assets/utf_ngo.png


